### ISSUE TITLE
PHP 7?

### ISSUE THREAD

**Issue by phanan** [lstrojny/functional-php#169]
The support for PHP 5.6 (and even 7.0) is ending by [the end of this year](https://secure.php.net/supported-versions.php). Should we make the lib PHP 7.1? Happy to work on it if positive.

**Comment by Kaishiyoku** [comment]
So...what's the status? PHP 5.6 is now officially unsupported. It would be great to stick with 7.1

**Comment by lstrojny** [comment]
My thought was to require PHP 7.x for functional 2 where I plan to fix various issues. See #141 for details.

**Comment by shainegordon** [comment]
We use this library successfully on PHP 7.1 based composer projects.

However, since upgrading all our projects to PHP 7.3, while still wanting to this excellent library, we have had to fork the source for 1.9.0 so that we can comment out `define('Functional\\…', …());` in `PartialAny.php` to avoid 
```
[ErrorException]                                                   
  Constants may only evaluate to scalar values, arrays or resources
```
on composer's `dumpautoload` process
