### ISSUE TITLE
Let the default callback argument to function some, none, and every be the identity function

### ISSUE THREAD

**Issue by KJSanchez** [lstrojny/functional-php#212]
Bet this would be helpful when you have just an array of booleans.

**Comment by lstrojny** [comment]
Same for `reject` and select `select` I guess? Sounds sensible to me

**Comment by jasonmm** [comment]
I created pull request #214 in response to this issue. The pull request does not include the `reject` and `select` functions because doing so did not seem to be as useful. If the `id` function is the default $callback for `reject` and `select` it would mean that every item in $collection would be rejected or selected. 

I was unable to think of a use case where this would be a common desired behavior. I'm happy to update the pull request if `reject` and `select` should be included.

**Comment by lstrojny** [comment]
`reject` with `id` would remove all truthy values while `select` with `id` would remove all falsy values. `array_filter` behaves like that. In conclusion I think I would add it.

**Comment by jasonmm** [comment]
I think #214 closes this issue.
