### ISSUE TITLE
Covinience of the reduce?

### ISSUE THREAD

**Issue by jbeja** [lstrojny/functional-php#76]
Is there any convenience or thought about putting the `$reduction` as the last argument in the function that take `reduce_right|left`?

**Comment by lstrojny** [comment]
Maybe I misunderstand you but it should be like that already:

```
$callback($value, $index, $collection, $initial);
```

**Comment by jbeja** [comment]
I meant : Why the `$initial|$reduction` is a the last argument of the function? Any thought why the notation is not: `$callback($initial, $value, $index, $collection)`, which to me is more convenient for most operation that could involve `reducing` without retyping all the arguments every time I need to use.

Are you assuming that the `$index` and the `$collection` are more useful?

**Comment by lstrojny** [comment]
@jbeja ah, thanks for clarifying, misunderstood you! The reason is consistency with the other functions, where the callee signature is always `$callback($value, $index, $collection)`. That’s why I went with adding `$reduction` as the fourth argument.

**Comment by lstrojny** [comment]
As changing it would be a B/C break I will close this issue. Hope that’s understandable.

**Comment by jwdunne** [comment]
Ah, this library is awesome other than this. 

Typical reduce/fold implementations take a callable with the following signature, where `a` and `b` are any types:

```
(initial: a, item: b): a
```

This *does* break consistency with other callbacks but that's intentional. In most cases, e.g `map` and `filter`, those functions are used with a unary function. With `reduce`, it takes a binary function. For `reduce` to behave as expected, imagine PHP had a function equivalent for every binary operator:

```
reduce_left([1, 2, 3], 'add', 0) == 6
reduce_left([1, 2, 3], 'mul', 1) == 6
```

In this case, for the usability and soundness of the `reduce_*` functions, you should perhaps reconsider the BC change so that it's consistent with typical `reduce`/`fold` implementations. The justification for this is that `reduce`/`fold` should act as if interleaving operators that have a Monoid structure:

```
reduce_left([1, 2, 3], 'add', 0) == 0 + 1 + 2 + 3
reduce_left([1, 2, 3], 'mul', 1) == 1 * 1 * 2 * 3
```

Perhaps, so as not to break BC compatibility, you could introduce `fold_left` and `fold_right` that does exhibit this behaviour? If I need reduce a collection, the first port of call is the docs to see whether the language/library is using the name `reduce` or `fold`.
