### ISSUE TITLE
Collection pipeline feature

### ISSUE THREAD

**Issue by povilasb** [lstrojny/functional-php#78]
Collectione pipeline is a nice design pattern to transform your collections: http://martinfowler.com/articles/collection-pipeline/.

It would be really nice if this library supported java 8 like streams (https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html):

    int sum = widgets.stream()
                      .filter(w -> w.getColor() == RED)
                      .mapToInt(w -> w.getWeight())
                      .sum();

I guess it should't be too hard. The transformation functions should return some kind of `Stream` instance instead of an `array`.

**Comment by lstrojny** [comment]
While I like collection pipelines I think this is out of scope for functional PHP.

**Comment by colinodell** [comment]
@lstrojny Would you be willing to reconsider this feature?  I love using your library, but sometimes I do have a need to chain multiple operations together.  Having both the functions and a collection pipeline exposing them would be amazing.

I'd be happy to write the PR if you're interested.  If not, perhaps I could create a separate package which pulls your functions into a pipeline class.

**Comment by lstrojny** [comment]
@colinodell given a good PR I am happy to reconsider.

**Comment by soutoner** [comment]
What about something like [Underscore's chain](http://underscorejs.org/#chain)? I have thought about an implementation in which a class that wraps the collection is created and all the functions provided by the library are implemented as method of that class. In that way, IDEs will provide auto completion.

Something like:

```php
chain([1, 2, 3])->map(function ($e) { return $e*2; })
                ->filter(function ($e) { return $e % 2 == 0; })
                ->value();
```

The drawback is that when a new function is defined in the library, it should be added to the collection-wrapper class as a method, and obviously the class will have tons of "dumb" lines of code but I don't think that will happen so frequently (I mean, to add a new function to the library).

Also I thought about a more "dynamic" implementation with some kind of `call_user_func` but in my humble opinion I think it would decrease the library quality because we start talking about throwing exceptions when you call a non-defined function, etc.

If you want I can make a pull request.

**Comment by FabioBatSilva** [comment]
BTW, I'm working on a streams API based on the java 8 implementation : https://github.com/FabioBatSilva/pipeline-streams
