### ISSUE TITLE
Shouldn't moving to PHP7 be a major version release? (1.0 = php5, 1.2 = php7)

### ISSUE THREAD

**Issue by ahungry** [lstrojny/functional-php#91]
According to most semantic versioning guidelines (and primarily the ones used by composer on most projects) it should go:

major.minor.bug

Where major allows non-backwards compatible changes, minor is always backwards compatible but offers new features, and bug is for general bugfix/maintenance.

In the case of the lstrojny/functional-php package, it is possible to have a composer.json with something like ~1.0 for the pinned functional-php version, run it on a PHP7 machine and end up with a composer.lock file that is no longer compatible on a PHP5.x machine (therefore requiring manually figuring out the last version that worked with PHP5.x and pinning to an exact version like 1.0.0).

For this reason, I strongly advocate in favor of making the PHP7+ release lstrojny/functional-php 2.x.x (don't be afraid to increment that major version!)

**Comment by jdreesen** [comment]
If you develop in a PHP 7 env but your production env is PHP 5 you should set [Composer's `platform` config](https://getcomposer.org/doc/06-config.md#platform) to the PHP version of your prod system and Composer will only install versions of the libs compatible with it ;)

**Comment by ahungry** [comment]
That's a great suggestion (thank you!) but the fact isn't just that the package changed the dependency - version 1.2 makes use of PHP7 only features, which means it is not backwards compatible with version 1.0 (environments that can run 1.0 will never be upgraded to 1.2 - luckily thanks to composer, but the versioning itself should handle this properly, unless there is just no desire to follow the versioning convention).

If I pin version ~1.0 I should expect to receive features/bugfixes up to but excluding version 2.0.0 which I would expect to be incompatible.

I guess I don't understand the versioning scheme being used (why lock into 1.x like this?)

**Comment by jdreesen** [comment]
Well, I'm not the author/maintainer of this package but I tend to agree regarding a major PHP version change.

However I just looked in the `composer.json` and it says `"php": ">=5.6.0"` for version 1.2 / master. In addition the travis builds seems to run fine with PHP 5.6 too and thus I'm not sure why you think that PHP 7 is required for the latest version?

Regarding the rise of the PHP minor version from 5.3 in v1.0 to 5.6 in v1.2 I think this is a valid change, even if PHP 5.6 supports more features and thus isn't fully backwards compatible, because PHP 5.3 is EOL'ed for quite some time now (even [PHP 5.5 security support ends in less than a month](https://secure.php.net/supported-versions.php)) and should not be used anymore.

**Comment by ahungry** [comment]
Ah that was my mistake (my own use case happened to be PHP7 on one machine PHP 5.5.9 on the Ubuntu 14.04 LTS machine - I completely forgot about PHP 5.6).

Still, I think altering the minimum viable PHP version should warrant more than a minor version bump on this end.

**Comment by lstrojny** [comment]
I have no plans so far to abandon 5.6 support. Closing for now.

**Comment by ahungry** [comment]
The issue was that you abandoned sub-5.6 support without doing a major version bump

**Comment by jdreesen** [comment]
The real issue is using unsupported PHP versions ;)
